export const techList = [
    // Languages
    { name: 'HTML5', slug: 'html5', icon: 'FaHtml5', color: '#E34F26' },
    { name: 'CSS3', slug: 'css3', icon: 'FaCss3Alt', color: '#1572B6' },
    { name: 'JavaScript', slug: 'javascript', icon: 'SiJavascript', color: '#F7DF1E' },
    { name: 'TypeScript', slug: 'typescript', icon: 'SiTypescript', color: '#3178C6' },
    { name: 'Python', slug: 'python', icon: 'FaPython', color: '#3776AB' },
    { name: 'Java', slug: 'java', icon: 'FaJava', color: '#ED8B00' },
    { name: 'C#', slug: 'csharp', icon: 'SiSharp', color: '#239120' },
    { name: 'C', slug: 'c', icon: 'SiC', color: '#A8B9CC' },
    { name: 'C++', slug: 'cplusplus', icon: 'SiCplusplus', color: '#00599C' },
    { name: 'Go', slug: 'go', icon: 'SiGo', color: '#00ADD8' },
    { name: 'Rust', slug: 'rust', icon: 'SiRust', color: '#DEA584' },
    { name: 'Kotlin', slug: 'kotlin', icon: 'SiKotlin', color: '#7F52FF' },
    { name: 'Swift', slug: 'swift', icon: 'SiSwift', color: '#FA7343' },
    { name: 'Dart', slug: 'dart', icon: 'SiDart', color: '#0175C2' },
    { name: 'PHP', slug: 'php', icon: 'FaPhp', color: '#777BB4' },
    { name: 'Ruby', slug: 'ruby', icon: 'SiRuby', color: '#CC342D' },
    { name: 'Scala', slug: 'scala', icon: 'SiScala', color: '#DC322F' },
    { name: 'Lua', slug: 'lua', icon: 'SiLua', color: '#000080' },
    { name: 'R', slug: 'r', icon: 'SiR', color: '#276DC3' },
    { name: 'Perl', slug: 'perl', icon: 'SiPerl', color: '#39457E' },
    { name: 'Haskell', slug: 'haskell', icon: 'SiHaskell', color: '#5D4F85' },
    { name: 'Elixir', slug: 'elixir', icon: 'SiElixir', color: '#4B275F' },
    { name: 'Zig', slug: 'zig', icon: 'SiZig', color: '#F7A41D' },

    // Frontend
    { name: 'React', slug: 'react', icon: 'FaReact', color: '#61DAFB' },
    { name: 'Next.js', slug: 'nextdotjs', icon: 'SiNextdotjs', color: '#111111' },
    { name: 'Vue.js', slug: 'vuedotjs', icon: 'FaVuejs', color: '#4FC08D' },
    { name: 'Nuxt.js', slug: 'nuxtdotjs', icon: 'SiNuxt', color: '#00DC82' },
    { name: 'Angular', slug: 'angular', icon: 'FaAngular', color: '#DD0031' },
    { name: 'Svelte', slug: 'svelte', icon: 'SiSvelte', color: '#FF3E00' },
    { name: 'Astro', slug: 'astro', icon: 'SiAstro', color: '#FF5D01' },
    { name: 'Remix', slug: 'remix', icon: 'SiRemix', color: '#3992FF' },
    { name: 'Gatsby', slug: 'gatsby', icon: 'SiGatsby', color: '#663399' },
    { name: 'Tailwind CSS', slug: 'tailwindcss', icon: 'SiTailwindcss', color: '#06B6D4' },
    { name: 'Bootstrap', slug: 'bootstrap', icon: 'FaBootstrap', color: '#7952B3' },
    { name: 'Material UI', slug: 'mui', icon: 'SiMui', color: '#007FFF' },
    { name: 'Vite', slug: 'vite', icon: 'SiVite', color: '#646CFF' },
    { name: 'Webpack', slug: 'webpack', icon: 'SiWebpack', color: '#8DD6F9' },

    // Backend
    { name: 'Node.js', slug: 'nodedotjs', icon: 'FaNodeJs', color: '#339933' },
    { name: 'FastAPI', slug: 'fastapi', icon: 'SiFastapi', color: '#009688' },
    { name: 'Django', slug: 'django', icon: 'SiDjango', color: '#092E20' },
    { name: 'Flask', slug: 'flask', icon: 'SiFlask', color: '#111111' },
    { name: 'PyTorch', slug: 'pytorch', icon: 'SiPytorch', color: '#EE4C2C' },
    { name: 'TensorFlow', slug: 'tensorflow', icon: 'SiTensorflow', color: '#FF6F00' },
    { name: 'NumPy', slug: 'numpy', icon: 'SiNumpy', color: '#013243' },
    { name: 'Pandas', slug: 'pandas', icon: 'SiPandas', color: '#150458' },
    { name: 'Scikit-learn', slug: 'scikitlearn', icon: 'SiScikitlearn', color: '#F0923B' },
    { name: 'OpenCV', slug: 'opencv', icon: 'SiOpencv', color: '#5C3EE8' },
    { name: 'Jupyter', slug: 'jupyter', icon: 'SiJupyter', color: '#F37626' },
    { name: 'Poetry', slug: 'poetry', icon: 'SiPoetry', color: '#60A6E0' },
    { name: 'Ruby on Rails', slug: 'rubyonrails', icon: 'SiRubyonrails', color: '#CC0000' },
    { name: 'Spring Boot', slug: 'springboot', icon: 'SiSpringboot', color: '#6DB33F' },
    { name: 'Laravel', slug: 'laravel', icon: 'FaLaravel', color: '#FF2D20' },
    { name: 'Express', slug: 'express', icon: 'SiExpress', color: '#111111' },
    { name: 'Fastify', slug: 'fastify', icon: 'SiFastify', color: '#000000' },
    { name: 'NestJS', slug: 'nestjs', icon: 'SiNestjs', color: '#E0234E' },
    { name: 'GraphQL', slug: 'graphql', icon: 'SiGraphql', color: '#E10098' },
    { name: '.NET', slug: 'dotnet', icon: 'SiDotnet', color: '#512BD4' },
    { name: 'Strapi', slug: 'strapi', icon: 'SiStrapi', color: '#4945FF' },

    // Mobile
    { name: 'Flutter', slug: 'flutter', icon: 'SiFlutter', color: '#02569B' },
    { name: 'React Native', slug: 'reactnative', icon: 'FaReact', color: '#61DAFB' },
    { name: 'SwiftUI', slug: 'swiftui', icon: 'SiSwift', color: '#FA7343' },
    { name: 'Ionic', slug: 'ionic', icon: 'SiIonic', color: '#3880FF' },

    // Database
    { name: 'PostgreSQL', slug: 'postgresql', icon: 'SiPostgresql', color: '#4169E1' },
    { name: 'MySQL', slug: 'mysql', icon: 'SiMysql', color: '#4479A1' },
    { name: 'SQLite', slug: 'sqlite', icon: 'SiSqlite', color: '#003B57' },
    { name: 'MongoDB', slug: 'mongodb', icon: 'SiMongodb', color: '#47A248' },
    { name: 'Redis', slug: 'redis', icon: 'SiRedis', color: '#DC382D' },
    { name: 'Elasticsearch', slug: 'elasticsearch', icon: 'SiElasticsearch', color: '#005571' },
    { name: 'Supabase', slug: 'supabase', icon: 'SiSupabase', color: '#3ECF8E' },
    { name: 'Firebase', slug: 'firebase', icon: 'SiFirebase', color: '#FFCA28' },
    { name: 'MariaDB', slug: 'mariadb', icon: 'SiMariadb', color: '#003545' },
    { name: 'PlanetScale', slug: 'planetscale', icon: 'SiPlanetscale', color: '#000000' },
    { name: 'Prisma', slug: 'prisma', icon: 'SiPrisma', color: '#2D3748' },

    // Tools & DevOps
    { name: 'Docker', slug: 'docker', icon: 'FaDocker', color: '#2496ED' },
    { name: 'Kubernetes', slug: 'kubernetes', icon: 'SiKubernetes', color: '#326CE5' },
    { name: 'Terraform', slug: 'terraform', icon: 'SiTerraform', color: '#7B42BC' },
    { name: 'Git', slug: 'git', icon: 'FaGit', color: '#F05032' },
    { name: 'GitHub', slug: 'github', icon: 'FaGithub', color: '#181717' },
    { name: 'GitLab', slug: 'gitlab', icon: 'SiGitlab', color: '#FC6D26' },
    { name: 'Bitbucket', slug: 'bitbucket', icon: 'SiBitbucket', color: '#0052CC' },
    { name: 'GitHub Actions', slug: 'githubactions', icon: 'SiGithubactions', color: '#2088FF' },
    { name: 'Jenkins', slug: 'jenkins', icon: 'SiJenkins', color: '#D33833' },
    { name: 'CircleCI', slug: 'circleci', icon: 'SiCircleci', color: '#343434' },
    { name: 'Linux', slug: 'linux', icon: 'FaLinux', color: '#FCC624' },
    { name: 'Vercel', slug: 'vercel', icon: 'SiVercel', color: '#111111' },
    { name: 'Netlify', slug: 'netlify', icon: 'SiNetlify', color: '#00C7B7' },
    { name: 'Figma', slug: 'figma', icon: 'FaFigma', color: '#F24E1E' },
    { name: 'Postman', slug: 'postman', icon: 'SiPostman', color: '#FF6C37' },
    { name: 'Jira', slug: 'jira', icon: 'SiJira', color: '#0052CC' },
    { name: 'Grafana', slug: 'grafana', icon: 'SiGrafana', color: '#F46800' },
    { name: 'Prometheus', slug: 'prometheus', icon: 'SiPrometheus', color: '#E6522C' },
    { name: 'n8n', slug: 'n8n', icon: 'SiN8N', color: '#EA4B71' },
    { name: 'Zapier', slug: 'zapier', icon: 'SiZapier', color: '#FF4A00' },

    // AI
    { name: 'Google Gemini', slug: 'googlegemini', icon: 'SiGooglegemini', color: '#1C7BF1' },
    { name: 'Claude', slug: 'anthropic', icon: 'SiClaude', color: '#D4A574' },
    { name: 'Hugging Face', slug: 'huggingface', icon: 'SiHuggingface', color: '#FFD21E' },
    { name: 'LangChain', slug: 'langchain', icon: 'SiLangchain', color: '#1C3C3C' },
    { name: 'OpenRouter', slug: 'openrouter', icon: 'SiOpenrouter', color: '#6366F1' },

    // Cloud
    { name: 'AWS', slug: 'amazonaws', icon: 'FaAws', color: '#FF9900' },
    { name: 'Azure', slug: 'microsoftazure', icon: 'VscAzure', color: '#0078D4' },
    { name: 'Google Cloud', slug: 'googlecloud', icon: 'SiGooglecloud', color: '#4285F4' },
    { name: 'DigitalOcean', slug: 'digitalocean', icon: 'SiDigitalocean', color: '#0080FF' },
    { name: 'Cloudflare', slug: 'cloudflare', icon: 'SiCloudflare', color: '#F38020' },
];
